---

services:
  - id: 1
    name: Black bins/sacks
    feature_types:
      - name: Black 240L
        description:
  - id: 2
    name: Recycling
    feature_types:
      - name: Green 240L
        description:
  - id: 3
    name: Garden waste
    feature_types:
      - name: Brown 240L
        description:
  - id: 4
    name: Glass collection
    feature_types:
      - name: Black Box 55L
        description:

