---

services:
  - id: 1
    name: Refuse
    esd_url: http://id.esd.org.uk/service/524
    feature_types:
      - name: Black 240L
        description:
  - id: 2
    name: Recycling
    esd_url: http://id.esd.org.uk/service/1130
    feature_types:
      - name: Green 240L
        description:
  - id: 3
    name: Garden waste
    esd_url: http://id.esd.org.uk/service/530
    feature_types:
      - name: Brown 240L
        description:
  - id: 4
    name: Glass collection
    esd_url: http://id.esd.org.uk/service/1130
    feature_types:
      - name: Black Box 55L
        description:

